### ISSUE TITLE
Fullscreen controls does not work with iOS devices. ver 0.7.x

### ISSUE THREAD

**Issue by xSignificant** [mister-ben/videojs-mobile-ui#100]
Having issues with iOS devices with this plugin.

The control bar is not shown when in full screen. 
All Fullscreen controls do not work: 
- Rotate to landscape to enter Fullscreen
- Lock to fullscreen on rotate
- Always lock to landscape when entering fullscreen (works even when device rotation is disabled/non-functional)

**Comment by mister-ben** [comment]
iOS's fullscreen does not allow anything including controls to be overlaid in fullscreen. You can use the [`preferFullWindow` option](https://videojs.com/guides/options/#preferfullwindow) to make Video.js fill the browser instead of actual fullscreen if you prefer, then the buttons can show.

iOS doesn't support the orientation lock API yet, although it's coming. It's apparently working in Safari technical preview, although I've not been able to try it out yet.
