### ISSUE TITLE
[mobile] Double pause icon

### ISSUE THREAD

**Issue by rtritto** [mister-ben/videojs-mobile-ui#85]
![image](https://user-images.githubusercontent.com/40242971/203650509-5ae02060-cf82-46e6-ad78-7ad0bc38ca90.png)

https://user-images.githubusercontent.com/40242971/203852618-697aa05e-7f7b-4891-a201-212907fbbfe6.mp4

[Repro](https://stackblitz.com/edit/vercel-next-js-gkihef)

## Details
`scss` content:
```scss
@charset 'utf-8';
@import 'video.js/src/css/video-js.scss';
@import 'videojs-mobile-ui/src/plugin.css';
```

## Versions
_video.js_: 8.0.2
_videojs-mobile-ui_: 1.0.0

**Comment by mister-ben** [comment]
I can't reproduce. Do you have a simple live example?

**Comment by rtritto** [comment]
Added a video and tested with _video.js_ v8.0.2.

**Comment by mister-ben** [comment]
A video isn't any more useful to reproduce an issue as a sreenshot unfortunately. Can you add a reproduceable, live example?

**Comment by rtritto** [comment]
Added repo

**Comment by mister-ben** [comment]
This is because sass is changing the order of the CSS it outputs, putting the videojs-mobile-ui styles before the video.js styles. It also occurs in your example if I change the versions to 0.7.0/^7. I could make the styles in this plugin more specific, but I imagine it's not the only problem you'll run into if the order of css isn't preserved.

**Comment by rtritto** [comment]
@mister-ben any updates?

**Comment by rtritto** [comment]
@mister-ben do you have a workaround?
